spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:todo}"
    username: ${DB_USER:todo}
    password: ${DB_PASS:todo}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:7000/realms/TodoApp/protocol/openid-connect/certs

app:
  jwt-converter:
    resource-id: todo-app-client
    principal-attribute: preferred_username

server:
  port: 7001
  servlet:
    context-path: /api
